main: com.mengcraft.logintp.Main
name: LoginTeleport
version: ${project.version}
author: mengcraft.com
website: http://www.mengcraft.com/

commands:
  logintp:
    description: None.
    permission: logintp.admin
