main: com.mengcraft.bukkit.LoginTeleport
name: LoginTeleport
version: ${project.version}
website: http://www.mengcraft.com/

commands:
  login-tp:
    description: Basic command.
    permission: server.admin
